### ISSUE TITLE
ggpairs() doesn't handle column names with commas in them

### ISSUE THREAD

**Issue by jonathon-love** [ggobi/ggally#204] opened 2016-09-30 03:43 UTC
hi,
the following:

    data <- data.frame(a=1,b=2)
    dimnames(data)[[2]][[1]] <- 'd,h'
    ggpairs(data)

results in:

    Error in parse(text = x) : <text>:1:2: unexpected ','
    1: d,
         ^

i've tried tracking the issue myself, but there's only one call to `parse()` in GGally, and it can't be the culprit.

any tips on where this could be occurring?

with thanks

jonathon

**Comment by jonathon-love** [comment] 2016-09-30 03:53
in order to work around this issue, i just replaced all the column names with numbers and manually specified the columnLabels, but this leads to unexpected behaviour as well.

if you call the two columns 1 and 2, then your ggpairs plot will be a single point with an x of 1, and a y of 2. one can see how the use of `parse()` would be creating this issue too.

with thanks

**Comment by schloerke** [comment] 2016-10-16 20:47
Hi Jonathon,

Doing a traceback on the error, the issue is coming from ggplot2's aes_string() function.

```r
traceback()
9: parse(text = x)
8: FUN(X[[i]], ...)
7: lapply(mapping, function(x) {
       if (is.character(x)) {
           parse(text = x)[[1]]
       }
       else {
           x
       }
   })
6: aes_string(x = xColName, y = yColName) at ggpairs.R#852
5: add_and_overwrite_aes(aes_string(x = xColName, y = yColName), 
       mapping) at ggpairs.R#852
4: add_and_overwrite_aes(add_and_overwrite_aes(aes_string(x = xColName, 
       y = yColName), mapping), types$mapping) at ggpairs.R#783
3: FUN(X[[i]], ...)
2: lapply(seq_len(nrow(dataTypes)), function(i) {
       plotType <- dataTypes[i, "plotType"]
       posX <- dataTypes[i, "posX"]
       posY <- dataTypes[i, "posY"]
       xColName <- dataTypes[i, "xVar"]
       yColName <- dataTypes[i, "yVar"]
       if (posX > posY) {
           types <- upper
       }
       else if (posX < posY) {
    ... at ggpairs.R#766
1: ggpairs(data)
```

This is something that is out of GGally's hands unfortunately.  With a custom column name that uses a comma, I would not know how to make a plot using ggplot2 qplot function.


Correct, the way to work around this is to use a simple column name and use the column labels.  
```r
ggpairs(data.frame(1,2), columnLabels = c("A,B", "C,D"))
```
![screen shot 2016-10-16 at 4 46 36 pm](https://cloud.githubusercontent.com/assets/93231/19420750/271a2cd8-93c0-11e6-8e01-5787c7b69962.png)

Since there is a way to work around this and the plot above is expected behavior, I'm going to close the issue.

- Barret

**Closed by schloerke** 2016-10-16 20:47 UTC
