### ISSUE TITLE
Corrupted message

### ISSUE THREAD

**Issue by ArthurPERE** [ggobi/ggally#380] opened 2020-08-19 15:47 UTC
Hello

I'm in the version 2.0.0 of GGally with 3.6.3 R version

When i do this :

```r
data(tips, package = "reshape")
GGally::ggally_cor(tips, mapping = ggplot2::aes_string(x = "total_bill", y = "tip"))
```
The graph that result  have corrupted message at the place of `Corr:number`.
![Rplot](https://user-images.githubusercontent.com/9747808/90658452-e4f26b00-e243-11ea-9f9c-5ba80aedbaac.png)
like that figure.

Thanks,
Arthur

**Comment by schloerke** [comment] 2021-03-07 20:32
Duplicate of https://github.com/ggobi/ggally/issues/377

**Closed by schloerke** 2021-03-07 20:32 UTC
