### ISSUE TITLE
ggcoef_compare variable_labels no longer able to specify order

### ISSUE THREAD

**Issue by tiffanysara** [ggobi/ggally#450] opened 2022-10-06 22:51 UTC
I'm working with `ggcoef_compare` to plot coefficients from two separate models. I want to specify the variable order.

The issue: my code worked perfectly back in August, but it no longer specifies the correct variable order today. I've updated all the necessary packages (ggplot2, GGally), but I can't figure out what I'm doing wrong.

It's hard to provide a reproduce example of my code because I'm working with spatial models, but here is the code for my plot:

```r
models <- list("OLS" = ols, "Spatial Error" = err)

ggcoef_compare(models, 
               variable_labels = c(
                 localtaxrate = "Local Tax Rate",
                 unemprate = "Unemployment Rate",
                 gini_mean = "Gini",
                 theil_race = "Racial Segregation",
                 pctblack = "Percent Black",
                 `log(pop)` = "Population (log)"),
               facet_labeller = label_wrap_gen(15),
               conf.int = TRUE, conf.level = 0.95, 
               significance = NULL)
```
When I run this code, the plot displays variables in the following order: Gini, Local Tax Rate, Population, Percent Black, Racial Segregation, Unemployment Rate. I should also note that when I run my models (`ols` and `err`), I order the variables the same way I list them in my code for `ggcoef_compare`.

**Comment by larmarange** [comment] 2022-10-07 09:04
Dear @tiffanysara 

there have been some bug fixes regarding `ggcoef_compare()` in the dev version of `GGally` as well as in a PR not yet merged, cf. #448 

Could you try to test your code with the last version of `ggcoef_compare()` by using `remotes::install_github("ggobi/ggally#448")` to install the code from that PR.

The expected behaviour of `ggcoef_compare()` is to plot the coefficient in the order of the model, as returned by `broom.helpers::tidy_plus_plus()`.
According to your message, it seems that they are plotted in alphabetical order, a bug that should be fixed in #448 

The `variable_labels` has no impact on the order of the variables on the plot.

``` r
library(GGally)
#> Le chargement a nécessité le package : ggplot2
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
library(broom.helpers)

mod1 <- lm(Fertility ~ ., data = swiss)
mod2 <- step(mod1, trace = 0)
mod3 <- lm(Fertility ~ Agriculture + Education * Catholic, data = swiss)
models <- list("Full model" = mod1, "Simplified model" = mod2, "With interaction" = mod3)

mod1 |> 
  tidy_plus_plus() |> 
  dplyr::select(term, variable, var_label, estimate)
#> # A tibble: 5 × 4
#>   term             variable         var_label        estimate
#>   <chr>            <chr>            <chr>               <dbl>
#> 1 Agriculture      Agriculture      Agriculture        -0.172
#> 2 Examination      Examination      Examination        -0.258
#> 3 Education        Education        Education          -0.871
#> 4 Catholic         Catholic         Catholic            0.104
#> 5 Infant.Mortality Infant.Mortality Infant.Mortality    1.08

models |> 
  ggcoef_compare(type = "f")
```

![](https://i.imgur.com/JKBxkTs.png)

``` r

models |> 
  ggcoef_compare(
    variable_labels = c(Catholic = "cath.", Examination = "ex."),
    type = "f"
  )
#> ✖ `Examination` terms have not been found in `x`.
#> ✖ `Examination` terms have not been found in `x`.
```

![](https://i.imgur.com/GzVdOWy.png)

<sup>Created on 2022-10-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

There is an open question regarding the possibility of changing the order of the variables using the `include` parameter. It is not possible right now, but it is an good question for the `broom.helpers` package and I have open an issue to discuss it https://github.com/larmarange/broom.helpers/issues/183

**Comment by tiffanysara** [comment] 2022-10-07 20:59
Hi @larmarange,

Thank you for the helpful reply. 

I tried running the following code:
`remotes::install_github("ggobi/ggally#448")`
But received this error:
Downloading GitHub repo larmarange/ggally@issue447
`Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/larmarange/ggally/tarball/issue447' `

**Comment by larmarange** [comment] 2022-10-07 22:04
Since my message, that PR has been merged into the dev version. 

Could you try `remotes::install_github("ggobi/ggally")` ?

**Comment by tiffanysara** [comment] 2022-10-10 21:03
@larmarange 

my code works now -- thank you!!

**Comment by schloerke** [comment] 2022-10-11 15:00
Works. Closing

**Closed by schloerke** 2022-10-11 15:00 UTC
